/**
 * Created by yanhuiyi on 4/13/15.
 */
module.exports = exports = {
    options: {
        banner: '/*! Generated by Clam: <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd HH:MM:ss") %> */\n',
            beautify: {
            ascii_only: true
        }
    },
    main: {
        files: [
            {
                expand: true,
                cwd: 'build/',
                src: ['**/*.js', '!**/*-min.js'],
                dest: 'build/',
                // ext: '-min.js'
                ext: '.js'
            }
        ]
    }
};